services:
  comment-service:
    build: ./comment-service
    ports:
      - "4004:4004"
    env_file:
      - ./comment-service/.env
    depends_on:
      - mongo_comment

  auth-service:
    build: ./auth-service
    ports:
      - "4000:4000"
    env_file:
      - ./auth-service/.env
    depends_on:
      - mongo_auth

  post-service:
    build: ./post-service
    ports:
      - "4002:4002"
    env_file:
      - ./post-service/.env
    depends_on:
      - mongo_post

  user-service:
    build: ./user-service
    ports:
      - "4001:4001"
    env_file:
      - ./user-service/.env
    depends_on:
      - mongo_user
    volumes:
       - ./user-service/uploads:/app/uploads
  gateway:
    build: ./gateway
    ports:
      - "3001:3001"
    depends_on:
      - auth-service
      - user-service
      - post-service
      - comment-service
    volumes: 
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./user-service/uploads:/app/uploads

      

  # MongoDB pour auth-service
  mongo_auth:
    image: mongo
    container_name: breezy-mongo-auth
    ports:
      - "27017:27017"
    volumes:
      - auth_data:/data/db

  # MongoDB pour user-service
  mongo_user:
    image: mongo
    container_name: breezy-mongo-user
    ports:
      - "27018:27017"
    volumes:
      - user_data:/data/db

  # MongoDB pour post-service
  mongo_post:
    image: mongo
    container_name: breezy-mongo-post
    ports:
      - "27019:27017"
    volumes:
      - post_data:/data/db

#  MongoDB pour comment-service
  mongo_comment:
    image: mongo
    container_name: breezy-mongo-comment
    ports:
      - "27020:27017"
    volumes:
      - comment_data:/data/db

volumes:
  auth_data:
  user_data:
  post_data:
  comment_data:
