services:
  language-service:
    build: ./language-service
    ports:
      - "4007:4007"
    env_file:
      - ./language-service/.env
    depends_on:
      - mongo_language

  messaging-service:
    build: ./messaging-service
    ports:
      - "4006:4006"
    env_file:
      - ./messaging-service/.env
    depends_on:
      - mongo_messaging

  comment-service:
    build: ./comment-service
    ports:
      - "4003:4003"
    env_file:
      - ./comment-service/.env
    depends_on:
      - mongo_comment

  auth-service:
    build: ./auth-service
    ports:
      - "4000:4000"
    env_file:
      - ./auth-service/.env
    depends_on:
      - mongo_auth

  post-service:
    build: ./post-service
    ports:
      - "4002:4002"
    env_file:
      - ./post-service/.env
    depends_on:
      - mongo_post

  user-service:
    build: ./user-service
    ports:
      - "4001:4001"
    env_file:
      - ./user-service/.env
    depends_on:
      - mongo_user
    volumes:
      -  ./user-service/uploads:/app/uploads

  notification-service:
    build: ./notification-service
    ports:
      - "4005:4005"
    env_file:
      - ./notification-service/.env
    depends_on:
      - mongo_notification

  gateway:
    build: ./gateway
    ports:
      - "3001:3001"
      - "443:443"  # ✅ HTTPS
    depends_on:
      - auth-service
      - user-service
      - post-service
      - comment-service

      - notification-service
      - messaging-service
      - language-service

      
    volumes: 
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./user-service/uploads:/app/uploads
      - ./certs:/etc/nginx/certs:ro  # ✅ Monte les certificats



  # MongoDB pour auth-service
  mongo_auth:
    image: mongo
    container_name: breezy-mongo-auth
    ports:
      - "27017:27017"
    volumes:
      - auth_data:/data/db

  # MongoDB pour user-service
  mongo_user:
    image: mongo
    container_name: breezy-mongo-user
    ports:
      - "27018:27017"
    volumes:
      - user_data:/data/db

  # MongoDB pour post-service
  mongo_post:
    image: mongo
    container_name: breezy-mongo-post
    ports:
      - "27019:27017"
    volumes:
      - post_data:/data/db

#  MongoDB pour comment-service
  mongo_comment:
    image: mongo
    container_name: breezy-mongo-comment
    ports:
      - "27020:27017"
    volumes:
      - comment_data:/data/db


  # MongoDB pour messaging-service
  mongo_messaging:
    image: mongo
    container_name: breezy-mongo-messaging
    ports:
      - "27021:27017"
    volumes:
      - messaging_data:/data/db

  # MongoDB pour language-service
  mongo_language:
    image: mongo
    container_name: breezy-mongo-language
    ports:
      - "27023:27017"
    volumes:
      - language_data:/data/db

#  MongoDB pour notification-service
  mongo_notification:
    image: mongo
    container_name: breezy-mongo-notification
    ports:
      - "27022:27017"
    volumes:
      - notification_data:/data/db

volumes:
  auth_data:
  user_data:
  post_data:
  comment_data:
  notification_data:
  messaging_data:
  language_data:
