events {
    worker_connections 1024;
}

http {
    upstream auth_service {
        server auth-service:4000;
    }

    upstream user_service {
        server user-service:4001;
    }

      upstream post_service {
        server post-service:4002;
    }

       upstream comment_service {
        server comment-service:4003;
    }

    server {
        listen 3001;

        location = /authenticate {
        internal;
        proxy_pass http://auth_service/auth/authenticate;
        proxy_pass_request_body off;
        proxy_set_header Content-Length "";
        proxy_set_header X-Original-URI $request_uri;
        proxy_set_header Authorization $http_authorization;
     }


        location /auth/ {                  
            #serveur publique
            proxy_pass http://auth_service/;
            rewrite ^/auth(/.*)$ $1 break;
        }

        location /user/ {
            auth_request /authenticate;
proxy_set_header X-User-Id $http_x_user_id;
proxy_set_header X-User-Username $http_x_user_username;
proxy_set_header X-User-Role $http_x_user_role;

            proxy_pass http://user_service/;
            rewrite ^/user(/.*)$ $1 break;
        }
        
        location /post/ {
            auth_request /authenticate;
#    proxy_set_header X-User-Id $upstream_http_x_user_id;
#     proxy_set_header X-User-Username $upstream_http_x_user_username;
#     proxy_set_header X-User-Role $upstream_http_x_user_role;
            proxy_pass_request_headers on;
            proxy_pass http://post_service/;
            rewrite ^/post(/.*)$ $1 break;
        }

         location /comment/ {
            auth_request /authenticate;
            proxy_set_header X-User-id $upstream_http_x_user_id;
            proxy_set_header X-User-username $upstream_http_x_user_username;
            proxy_set_header X-User-role $upstream_http_x_user_role;
            proxy_pass http://comment_service/;
            rewrite ^/comment(/.*)$ $1 break;
        }
    }
}
