import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import RedirectIfAuthenticated from "../context/RedirectIfAuthenticated";

import { ToggleProvider } from "@/context/ToggleTargetComponentContext";
import NavbarClient from "@/components/NavbarClient";
import NotificationsPC from "@/components/NotificationsPC"; // ✅ à importer
import { AuthProvider } from "../context/AuthContext";
import ProtectedRoute from "../context/ProtectedRoute";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const hideNavbar = ["/", "/connection", "/userCreation"];

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ToggleProvider>
          <AuthProvider>
            {/* ✅ Navbar (une seule fois) */}
            <NavbarClient hideNavbar={hideNavbar} />

            {/* ✅ Notifications visibles si toggle activé */}
            <NotificationsPC />

            {/* ✅ Le reste de l'app */}
              <RedirectIfAuthenticated>
                <ProtectedRoute>
                  {children}
                </ProtectedRoute>
              </RedirectIfAuthenticated>

          </AuthProvider>
        </ToggleProvider>
      </body>
    </html>
  );
}
