import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import NavbarClient from "@/components/NavbarClient";
import { use } from "react";
import {AuthProvider} from "../context/AuthContext"
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const hideNavbar = ["/", "/connection", "/userCreation"];

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          {children}
        </AuthProvider>
        <NavbarClient hideNavbar={hideNavbar} />
      </body>
    </html>
  );
}
